baseURL = "https://www.thefoodmongeratx.comw"
languageCode = "en-us"
title = "FoodMongerATX: Austin Texas Hops and Grains"
theme="restaurant-hugo-theme-master"
summaryLength = "7"

# Menu
[menu]

    [[menu.nav]]
    name = "Home"
    URL = ""
    weight = 1
	
    [[menu.nav]]
    name = "Truck Menu"
    URL = "truck"
    weight = 2

    [[menu.nav]]
    name = "Catering Menu"
    URL = "catering"
    weight = 3

    [[menu.nav]]
    name = "Contact Us"
    URL = "contact"
    weight = 4

# Global Settings
[params]
logo = "images/logo.png"

[params.heroArea]
enable = true
[params.heroImg ] 
url =  "images/fm-header.jpg" 

#gallery item

[params.gallery]
enable = false
title= "Featured items at <span>Hops and Grains</span>"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-2.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-3.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-4.jpg"

[params.about]
enable = true
title= "Come see <span>FoodMonger ATX</span> at Hops and Grains Brewery!"
bgImage = "images/cooker-img.png"
description= "Shawn and Vanessa have been friends for over a decade. Their shared passion for food led to hours and days filled with conversation of opening their own culinary adventure."
description2= "With a vision of fresh food and a freestyle menu, The Food Monger hatched in October of 2017. From handmade sauces to freshly pickled veggies to on-the-truck-cut fries and the freshest meat, their commitment to quality is unchallenged. Every item is prepared by Shawn and Vanessa. The ever-changing menu and the made-from-scratch items keep their minds thinking and your bellies hungry for more. Freestyle means no boundary on cuisines, flavors, or collaborations. Every venture is different, and that barely scratches the surface! The Food Monger has been blessed with a great support system of friends and family. This dream could not have gotten off the ground without our amazing customers."


#food Menu

[params.foodMenu]
enable = true
title = "Food Truck <span>MENU</span> at Hops "
description= "Come see us at Hops and Grains Brewery every Thursday thru Sunday"
subtitle = "All of our Food is Cooked Fresh to Order!"

[[params.foodMenu.item]]
title="Satchamo Queso"
description= "Creamy White Melted Cheese, Fresh Spinach, FM Pico, Roasted Green Chiles & FM Red Tortilla Chips"
price = "$ 6.50"

[[params.foodMenu.item]]
title="Satchamo Queso & Bacon Papas"
description= "Our Delicious Queso with added Bacon papas"
price = "$ 8.00"

[[params.foodMenu.item]]
title="Bacon & Cheeeeeese Quesadilla with FM Pico & FM Avocado Ranch"
description= ""
price = "$ 8.50"

[[params.foodMenu.item]]
title="HandCut Papas with FM Ketchup"
description= ""
price = "$ 4.00"

[[params.foodMenu.item]]
title="Parmesan Papas with FM Ketchup"
description= ""
price = "$ 4.75"

[[params.foodMenu.item]]
title="Fried Egg Sandwich"
description= "Fried Eggs, Spring Mix, FM Mustard & Tomato on a Toasted Brioche Bun"
price = "$ 8.50"

[[params.foodMenu.item]]
title="Bean & Quinoa Wrap"
description= "Black & Pinto Beans, Quinoa, Avocado Lime Sauce, Spring Mix, FM Pico"
price = "$ 9.75"

[[params.foodMenu.item]]
title="“Our Famous” Cluckers"
description= "Hand Cut & Breaded in Our Special FM Spice Mix (Chicken Tenders) with Avocado Ranch"
price = "$ 9.75"

[[params.foodMenu.item]]
title="The Healthy Buffalo Wrap"
description= "Cluckers Tossed in FM Buffalo Sauce, Spring Mix, FM Pico & FM Avocado Ranch"
price = "$ 10.00"

[[params.foodMenu.item]]
title="The Turkey Bacon Wrap"
description= "Roasted Turkey, 2 Slices of Wrights Thick Cut Bacon, Spring Mix, FM Pico & FM Avocado Ranch All Rolled Up in a 13’ Tortilla"
price = "$ 11.00"

[[params.foodMenu.item]]
title="The Nessa Burger"
description= "Ground Beef Burger with FM Pickles, Tomato, Spring Mix & FM Mustard on a Toasted Brioche Bun"
price = "$ 10.00"

[[params.foodMenu.item]]
title="Lavender Butter Cheese Burger"
description= "7oz Ground Beef Burger, Melted Fontina Cheese, FM Roasted Garlic Lavender Butter, Wrights Thick Cut Bacon, FM Pickles, & Caramelized Onions"
price = "$ 10.00"

[[params.foodMenu.disclaimer]]
title="All Food is Cooked Fresh to Order!"
description= "FM = Made Fresh from Scratch in Our Truck"
description2= "Add Cheese, Egg, Avocado $1 or (2)Bacon $1.5 to Any Item"
description3="*All Burgers Are Cooked Medium"


#subscription

[params.subscription]
enable = false
title= "SUBSCRIBE to our <span>NEWSLETTER</span>"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"

#Contact 

[params.contact]
enable = true
title= " <span> Contact Us </span> for catering and general information"
subtitle= "Lets talk about Catering"
description = "FoodMongerATX Catering and Food Truck"


#Footer 

[params.footer]
enable = true
contactInfoTitle = "Come eat with us at <span>HOPS&GRAINS</span>"
blogTitle = "LATEST <span>BLOG POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Plese follow <span>US</span> on social media"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "Hops and Grains Brewery - 507 Calles Street Suite 101 Austin, Tx 78723"
link = "https://www.google.com/maps/place/Hops+and+Grain+Brewing/@30.258262,-97.712588,15z/data=!4m5!3m4!1s0x0:0x7eb8bbb1adbddf3d!8m2!3d30.258262!4d-97.712588"

[[params.footer.contactItem]]
title="Email"
icon = "fa fa-envelope"
content = "shawn.thefoodmonger@gmail.com"
link = "mailto:shawn.thefoodmonger@gmail.com"

[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/thefoodmongeratx"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://instagram.com/foodmongeratx"


#Footer Copyright

#Footer Copyright Text
[params.footerCopyright]
enable = true
Text = "Copyright 2019 - All Rights Reserved. Population2.com"
day="Thursday - Friday: 5PM – 9PM"
day2="Saturday: 2PM – 8PM"
day3="Sunday: 2PM – 7PM"

#blog 
[params.blog]
enable = true
title = "Fresh <span>From</span> the <span>Kitchen</span>"


#catering Menu

[params.cateringMenu]
enable = true
title = "This is our <span>Catering MENU</span>"
subtitle = "Catering starts as low as $9 per person."
description = "We can deliver your food and set it up in your home or office, for larger parties we can also bring our food truck to your location. You can pick from one of our many trays, build your own bars, group entrees or protein platters. "

[[params.cateringMenu.disclaimer]]
title="All Food is Cooked Fresh to Order!"
description= "FM = Made Fresh from Scratch in Our Truck"
description2= "Add Cheese, Egg, Avocado $1 or (2)Bacon $1.5 to Any Item"
description3="*All Burgers Are Cooked Medium"

[[params.cateringMenu.item]]
title="Breakfast Sandwiches served on a Brioche Bun w/ FM Jalapeno Aioli"
description=" 2 Fried Egg with your choice of:"
options="Provolone or Cheddar Cheese & Bacon, FM Sausage, or FM Chorizo"
price="$9 per person"

[[params.cateringMenu.item]]
title="Build Your Own Breakfast Tacos Bar"
description=" Scrambled Eggs and your choice of two of the following:"
options="Bacon, FM Sausage, FM Chorizo, Potatoes or Re-Fried Beans"
description2= "Served with Tortillas & Salsa."
price="$9.5 per person"

[[params.cateringMenu.item]]
title="Sandwiches served on a Brioche Bun with your choice of Turkey, Ham, Grilled Chicken or Veggie"
description="All sandwiches are “dressed” with spring mix and tomato. FM Pickles on the side."
options="Provolone or Cheddar Cheese"
description2= "Jalapeno Aioli or FM Mustard"
price= "$10.5 per person"

[[params.cateringMenu.item]]
title="Build Your Own Taco Bar"
description=" Choose 1-2 of the following (Beef, Chicken or Pork)"
options="Served with Sautéed Peppers & Onions "
description2="Soft Flour Tortillas. "
description3="Includes Spanish Rice, Pinto or Black Beans FM Pico, Fresh Salsa, Sour Cream and Shredded Cheese"
price="$13.5 per person"

[[params.cateringMenu.item]]
title="Build Your Own Salad Bar"
description=" Spring Mix, Grilled Chicken, Shredded Carrots, Cucumbers, Cherry Tomatoes, Celery, Bacon, Shredded Cheese, Croutons, FM Vinaigrette & FM Avocado Ranch "
price= "$13.5 per person"
