baseURL = "/"
languageCode = "en-us"
title = "FoodMongerATX: Austin Texas Hops and Grains"
theme="restaurant-hugo-theme-master"
summaryLength = "7"


# Menu
[menu]
	
	[[menu.nav]]
    name = "Home"
    URL = ""
    weight = 1

    [[menu.nav]]
    name = "Truck Menu"
    URL = "menu"
    weight = 2

    [[menu.nav]]
    name = "Catering Menu"
    URL = "catering"
    weight = 3

    [[menu.nav]]
    name = "Features"
    URL = "features"
    weight = 4

    [[menu.nav]]
    name = "Contact Us"
    URL = "contact-us"
    weight = 5



# Global Settings
[params]
logo = "images/logo.png"


[params.heroArea]
enable = true
[params.heroImg ] 
url =  "images/fm-header.jpg" 


#gallery item

[params.gallery]
enable = true
title= "Featured <span>Menu</span>"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-2.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-3.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-4.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-1.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-2.jpg"

[[params.gallery.item]]
img = "images/slider/slider-img-3.jpg"


[params.about]
enable = true
title= "Check out <span>FoodMonger ATX</span> at Hops and Grains Brewery"
bgImage = "images/cooker-img.png"
description= "Shawn and Vanessa have been friends for over a decade. Their shared passion for food led to hours and days filled with conversation of opening their own culinary adventure."
description2= "With a vision of fresh food and a freestyle menu, The Food Monger hatched in October of 2017. From handmade sauces to freshly pickled veggies to on-the-truck-cut fries and the freshest meat, their commitment to quality is unchallenged. Every item is prepared by Shawn and Vanessa. The ever-changing menu and the made-from-scratch items keep their minds thinking and your bellies hungry for more. Freestyle means no boundary on cuisines, flavors, or collaborations. Every venture is different, and that barely scratches the surface! The Food Monger has been blessed with a great support system of friends and family. This dream could not have gotten off the ground without our amazing customers."



#food Menu

[params.foodMenu]
enable = true
title = "Food Monger Truck <span>MENU</span>"
description= "Come see us at Hops and Grains Brewery every Thursday thru Sunday"
subtitle = "MENU FEATURED AT HOPS AND GRAINS"

[[params.foodMenu.item]]
title="Satchamo Queso"
description= "Creamy White Melted Cheese, Fresh Spinach, FM Pico, Roasted Green Chiles & FM Red Tortilla Chips"
price = "$ 6.50"

[[params.foodMenu.item]]
title="Satchamo Queso & Bacon Papas"
description= "Our Delicious Queso with added Bacon papas"
price = "$ 8.00"

[[params.foodMenu.item]]
title="Bacon & Cheeeeeese Quesadilla with FM Pico & FM Avocado Ranch"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 8.50"

[[params.foodMenu.item]]
title="HandCut Papas with FM Ketchup"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 4.00"

[[params.foodMenu.item]]
title="Parmesan Papas with FM Ketchup"
description= "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim&&"
price = "$ 4.75"


[[params.foodMenu.item]]
title="Fried Egg Sandwich"
description= "Fried Eggs, Spring Mix, FM Mustard & Tomato on a Toasted Brioche Bun"
price = "$ 8.50"

[[params.foodMenu.item]]
title="Bean & Quinoa Wrap"
description= "Black & Pinto Beans, Quinoa, Avocado Lime Sauce, Spring Mix, FM Pico"
price = "$ 9.75"


[[params.foodMenu.item]]
title="“Our Famous” Cluckers"
description= "Hand Cut & Breaded in Our Special FM Spice Mix (Chicken Tenders) with Avocado Ranch"
price = "$ 9.75"

[[params.foodMenu.item]]
title="The Healthy Buffalo Wrap"
description= "Cluckers Tossed in FM Buffalo Sauce, Spring Mix, FM Pico & FM Avocado Ranch"
price = "$ 10.00"

[[params.foodMenu.item]]
title="The Turkey Bacon Wrap"
description= "Roasted Turkey, 2 Slices of Wrights Thick Cut Bacon, Spring Mix, FM Pico & FM Avocado Ranch All Rolled Up in a 13’ Tortilla"
price = "$ 11.00"

[[params.foodMenu.item]]
title="The Nessa Burger"
description= "Ground Beef Burger with FM Pickles, Tomato, Spring Mix & FM Mustard on a Toasted Brioche Bun"
price = "$ 10.00"

[[params.foodMenu.item]]
title="Lavender Butter Cheese Burger"
description= "7oz Ground Beef Burger, Melted Fontina Cheese, FM Roasted Garlic Lavender Butter, Wrights Thick Cut Bacon, FM Pickles, & Caramelized Onions"
price = "$ 10.00"


#subscription

[params.subscription]
enable = true
title= "SUBSCRIBE to our <span>NEWSLETTER</span>"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"

#Mailchimp subscription configaration 
formAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e"
formName = "b_f95ece2732a6e9925f2e70a61_b1e227529e"

#Contact 

[params.contact]
enable = true
title= "our <span> Contact Us </span>"
subtitle= "SIGN UP FOR EMAIL ALERTS"
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod"


#Footer 

[params.footer]
enable = true
contactInfoTitle = "CONTACT <span>INFO</span> "
blogTitle = "LATEST <span>BLOG POSTS</span>"
galleryTitle = "PHOTO <span>STREAM</span>"
socialTitle = "Follow <span>US</span>"

[[params.footer.contactItem]]
title="Telephone"
icon = "fa fa-phone"
content = "016742 323313"

[[params.footer.contactItem]]
title="Address"
icon = "fa fa-map-marker"
content = "1301 Calles St. Hops and Grains"

[[params.footer.contactItem]]
title="E mail"
icon = "fa fa-envelope"
content = "shawn@foodmongeratx.com - rest@mail.ru"

[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/foodmongeratx"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://instagram.com/foodmongeratx"


#Footer Copyright

#Footer Copyright Text
[params.footerCopyright]
enable = true
Text = "Copyright 2019 - All Rights Reserved. Population2.com"


#blog 
[params.blog]
enable = true
title = "Freshest <span>From</span> the <span>Menu</span>"









